spring:
  application:
    name: clouddriver

kubernetes:
  kubectl:
    executable: ${IT_BUILD_HOME}/kubectl
  enabled: true
  primaryAccount: account1
  accounts:
    - name: account1
      cacheIntervalSeconds: 10
      requiredGroupMembership: []
      providerVersion: V2
      permissions: {}
      dockerRegistries: []
      configureImagePullSecrets: true
      cacheThreads: 3
      namespaces: []
      omitNamespaces: []
      kinds: []
      omitKinds: []
      customResources: []
      cachingPolicies: []
      oauthScopes: []
      oAuthScopes: []
      onlySpinnakerManaged: true
      metrics: false
<<<<<<< HEAD
      kubeconfigFile: ${KUBECONFIGS_HOME}/kubecfg-${account1_containername}.yml  # File is automatically created during initialization
=======
      kubeconfigFile: ${IT_BUILD_HOME}/kubecfg.yml  # File is automatically created at runtime
>>>>>>> cc8094bef (fix(kube/test): Use kind instead of k3s (backport #5421) (#5451))
    - name: account2
      cacheIntervalSeconds: 30
      requiredGroupMembership: []
      providerVersion: V2
      permissions: {}
      dockerRegistries: []
      configureImagePullSecrets: true
      cacheThreads: 1
      namespaces:
      - default
      omitNamespaces: []
      kinds: []
      omitKinds: []
      customResources: []
      cachingPolicies: []
      oauthScopes: []
      oAuthScopes: []
      onlySpinnakerManaged: true
      metrics: false
<<<<<<< HEAD
      kubeconfigFile: ${KUBECONFIGS_HOME}/kubecfg-${account1_containername}.yml  # File is automatically created during initialization
=======
      kubeconfigFile: ${IT_BUILD_HOME}/kubecfg.yml  # File is automatically created at runtime

logging.level.com.netflix.spinnaker.cats.sql.cluster: INFO
logging.level.com.netflix.spinnaker.clouddriver.kubernetes.caching.agent.KubernetesCacheDataConverter: WARN
>>>>>>> cc8094bef (fix(kube/test): Use kind instead of k3s (backport #5421) (#5451))

sql:
  enabled: true
  taskRepository:
    enabled: true
  cache:
    enabled: true
    readBatchSize: 500
    writeBatchSize: 300
  scheduler:
    enabled: true
  connectionPools:
    default:
      default: true
      jdbcUrl: jdbc:tc:mysql:5.7.22://somehostname:someport/clouddriver?user=root?password=&
    tasks:
      jdbcUrl: jdbc:tc:mysql:5.7.22://somehostname:someport/clouddriver?user=root?password=&
  migration:
    jdbcUrl: jdbc:tc:mysql:5.7.22://somehostname:someport/clouddriver?user=root?password=&

redis:
  enabled: false
  cache:
    enabled: false
  scheduler:
    enabled: false
  taskRepository:
    enabled: false

services:
  fiat:
    baseUrl: http://fiat.net
  front50:
    baseUrl: http://front50.net
